import React from "react";
import { useNavigate } from "react-router-dom";
import { Clock, CheckCircle2, DollarSign, Wallet, ArrowRight } from "lucide-react";

// ─── Mock Data ───────────────────────────────────────────────────────────────

const MOCK_PENDING = [
  {
    id: "po-101",
    date: "2026-03-05",
    billNo: "PO-2026-03-05-A",
    submittedBy: "Kamal Perera (Subject Clerk)",
    itemCount: 42,
    originalTotal: 125400.00,
    priceChanges: 2,
  },
  {
    id: "po-102",
    date: "2026-03-05",
    billNo: "PO-2026-03-05-B",
    submittedBy: "Nimal Silva (Subject Clerk)",
    itemCount: 15,
    originalTotal: 45000.00,
    priceChanges: 0,
  },
  {
    id: "po-103",
    date: "2026-03-04",
    billNo: "PO-2026-03-04-C",
    submittedBy: "Kamal Perera (Subject Clerk)",
    itemCount: 28,
    originalTotal: 89200.50,
    priceChanges: 1,
  },
];

// ─── Main Component ──────────────────────────────────────────────────────────

const Approvals = () => {
  const navigate = useNavigate();

  // Dashboard metrics
  const stats = [
    { label: "Pending", value: 3, icon: Clock, colorClass: "text-amber-600", bgClass: "bg-amber-100" },
    { label: "Approved Today", value: 1, icon: CheckCircle2, colorClass: "text-green-600", bgClass: "bg-green-100" },
    { label: "Total This Week", value: "Rs. 42,500", icon: DollarSign, colorClass: "text-blue-600", bgClass: "bg-blue-100" },
    { label: "Budget Remaining", value: "Rs. 157,500", icon: Wallet, colorClass: "text-gray-500", bgClass: "bg-gray-100" },
  ];

  return (
    <div className="space-y-6 max-w-7xl mx-auto p-4 md:p-6 pb-24">
      
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-gray-900 tracking-tight">Pending Approvals</h1>
        <p className="text-sm text-gray-500 mt-1">Review and approve daily purchase orders generated by Subject Clerks.</p>
      </div>

      {/* KPI Cards Grid */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {stats.map((s) => (
          <div key={s.label} className="bg-white rounded-xl border border-gray-200 shadow-sm p-4 flex items-center gap-4 transition-shadow hover:shadow-md">
            <div className={`p-3 rounded-lg ${s.bgClass} flex-shrink-0`}>
              <s.icon className={`h-6 w-6 ${s.colorClass}`} />
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-0.5">{s.label}</p>
              <p className={`text-xl font-bold ${s.colorClass === "text-gray-500" ? "text-gray-900" : s.colorClass}`}>
                {s.value}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* Pending Approvals Table */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden flex flex-col">
        <div className="px-5 py-4 border-b border-gray-100 bg-gray-50/50">
          <h2 className="text-base font-bold text-gray-900">Purchase Orders Requiring Review</h2>
        </div>
        
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm whitespace-nowrap">
            <thead className="bg-gray-50 border-b border-gray-200 text-gray-500">
              <tr>
                <th className="px-5 py-3 font-semibold w-32">Date</th>
                <th className="px-5 py-3 font-semibold">Bill #</th>
                <th className="px-5 py-3 font-semibold hidden md:table-cell">Submitted By</th>
                <th className="px-5 py-3 font-semibold text-right w-24">Items</th>
                <th className="px-5 py-3 font-semibold text-right hidden sm:table-cell w-36">Original Total</th>
                <th className="px-5 py-3 font-semibold w-40">Price Changes</th>
                <th className="px-5 py-3 font-semibold text-right w-28">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {MOCK_PENDING.map((p) => (
                <tr key={p.id} className="hover:bg-gray-50/50 transition-colors group">
                  <td className="px-5 py-4 text-gray-500 font-medium">{p.date}</td>
                  <td className="px-5 py-4 font-bold text-gray-900">{p.billNo}</td>
                  <td className="px-5 py-4 text-gray-600 hidden md:table-cell">{p.submittedBy}</td>
                  <td className="px-5 py-4 text-right text-gray-700 font-medium">{p.itemCount}</td>
                  <td className="px-5 py-4 text-right hidden sm:table-cell font-bold text-gray-900">
                    Rs. {p.originalTotal.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </td>
                  <td className="px-5 py-4">
                    {p.priceChanges > 0 ? (
                      <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-bold bg-amber-100 text-amber-800 border border-amber-200">
                        {p.priceChanges} {p.priceChanges === 1 ? "change" : "changes"}
                      </span>
                    ) : (
                      <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-bold bg-green-100 text-green-800 border border-green-200">
                        No changes
                      </span>
                    )}
                  </td>
                  <td className="px-5 py-4 text-right">
                    <button 
                      onClick={() => navigate(`/approvals/${p.id}`)}
                      className="inline-flex items-center justify-center px-4 py-2 text-sm font-semibold text-blue-700 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 hover:border-blue-300 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors"
                    >
                      Review <ArrowRight className="h-3.5 w-3.5 ml-1.5" />
                    </button>
                  </td>
                </tr>
              ))}
              
              {MOCK_PENDING.length === 0 && (
                <tr>
                  <td colSpan="7" className="px-5 py-12 text-center text-gray-500">
                    <CheckCircle2 className="h-8 w-8 mx-auto text-green-400 mb-3" />
                    <p className="text-base font-medium text-gray-900">All caught up!</p>
                    <p className="text-sm">There are no purchase orders pending approval.</p>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
      
    </div>
  );
};

export default Approvals;