import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Eye, Download, Printer, FileText } from "lucide-react";

// ─── Mock Data ───────────────────────────────────────────────────────────────

const MOCK_INVOICES = [
  { 
    id: "inv-101", 
    billNo: "INV-2026-03-05-A", 
    date: "2026-03-05", 
    supplier: "Multi Purpose Co-operative Society Ltd, Gampaha", 
    grandTotal: 263500.00, 
    generatedBy: "System Auto" 
  },
  { 
    id: "inv-102", 
    billNo: "INV-2026-03-04-B", 
    date: "2026-03-04", 
    supplier: "AgriFresh Wholesale Distributors", 
    grandTotal: 145200.50, 
    generatedBy: "Admin_Perera" 
  },
  { 
    id: "inv-103", 
    billNo: "INV-2026-03-03-C", 
    date: "2026-03-03", 
    supplier: "Multi Purpose Co-operative Society Ltd, Gampaha", 
    grandTotal: 210850.00, 
    generatedBy: "System Auto" 
  },
  { 
    id: "inv-104", 
    billNo: "INV-2026-03-02-D", 
    date: "2026-03-02", 
    supplier: "Ceylon Meat Producers", 
    grandTotal: 89000.00, 
    generatedBy: "Admin_Perera" 
  },
];

// ─── Simple Inline Toast Hook & Component ────────────────────────────────────

function useToast() {
  const [toasts, setToasts] = useState([]);
  const toast = ({ title, description }) => {
    const id = Date.now();
    setToasts((p) => [...p, { id, title, description }]);
    setTimeout(() => setToasts((p) => p.filter((t) => t.id !== id)), 3000);
  };
  return { toast, toasts };
}

function ToastContainer({ toasts }) {
  if (toasts.length === 0) return null;
  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col gap-2 pointer-events-none">
      {toasts.map((t) => (
        <div 
          key={t.id} 
          className="bg-gray-900 text-white px-4 py-3 rounded-lg shadow-xl min-w-[250px] pointer-events-auto animate-in slide-in-from-bottom-5 fade-in duration-300"
        >
          <div className="font-semibold text-sm">{t.title}</div>
          {t.description && <div className="text-gray-300 text-xs mt-1">{t.description}</div>}
        </div>
      ))}
    </div>
  );
}

// ─── Main Component ──────────────────────────────────────────────────────────

const Invoices = () => {
  const navigate = useNavigate();
  const { toast, toasts } = useToast();

  const handleDownload = (billNo) => {
    toast({ title: "Download Started", description: `Downloading PDF for ${billNo}...` });
  };

  const handlePrint = (billNo) => {
    toast({ title: "Preparing Print", description: `Sending ${billNo} to printer spool...` });
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto p-4 md:p-6 pb-24">
      
      <ToastContainer toasts={toasts} />

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 tracking-tight">Invoices & Billing</h1>
          <p className="text-sm text-gray-500 mt-1">Manage and export system-generated purchase invoices.</p>
        </div>
      </div>

      {/* Data Table Card */}
      <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden flex flex-col">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm whitespace-nowrap">
            
            <thead className="bg-gray-50 border-b border-gray-200 text-gray-500">
              <tr>
                <th className="px-5 py-3.5 font-semibold">Bill #</th>
                <th className="px-5 py-3.5 font-semibold w-32">Date</th>
                <th className="px-5 py-3.5 font-semibold hidden md:table-cell max-w-[250px]">Supplier</th>
                <th className="px-5 py-3.5 font-semibold text-right w-40">Grand Total (Rs)</th>
                <th className="px-5 py-3.5 font-semibold hidden sm:table-cell w-40">Generated By</th>
                <th className="px-5 py-3.5 font-semibold w-36 text-center">Actions</th>
              </tr>
            </thead>
            
            <tbody className="divide-y divide-gray-100">
              {MOCK_INVOICES.map((inv) => (
                <tr key={inv.id} className="hover:bg-blue-50/40 transition-colors group">
                  
                  {/* Bill Number */}
                  <td className="px-5 py-4">
                    <div className="flex items-center gap-2">
                      <FileText className="h-4 w-4 text-gray-400 group-hover:text-blue-500" />
                      <span className="font-bold text-gray-900">{inv.billNo}</span>
                    </div>
                  </td>
                  
                  {/* Date */}
                  <td className="px-5 py-4 text-gray-600 font-medium">
                    {inv.date}
                  </td>
                  
                  {/* Supplier */}
                  <td className="px-5 py-4 hidden md:table-cell text-gray-500 max-w-[250px] truncate">
                    {inv.supplier}
                  </td>
                  
                  {/* Grand Total */}
                  <td className="px-5 py-4 text-right font-black text-gray-900 text-base">
                    Rs. {inv.grandTotal.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </td>
                  
                  {/* Generated By */}
                  <td className="px-5 py-4 hidden sm:table-cell">
                    <span className="inline-flex px-2 py-1 rounded bg-gray-100 text-gray-600 text-xs font-semibold">
                      {inv.generatedBy}
                    </span>
                  </td>
                  
                  {/* Actions */}
                  <td className="px-5 py-4 text-center">
                    <div className="flex items-center justify-center gap-1.5">
                      <button 
                        onClick={() => navigate(`/invoices/${inv.id}`)}
                        className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-md transition-colors focus:outline-none"
                        title="View Invoice Details"
                      >
                        <Eye className="h-4 w-4" />
                      </button>
                      <button 
                        onClick={() => handleDownload(inv.billNo)}
                        className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-md transition-colors focus:outline-none"
                        title="Download PDF"
                      >
                        <Download className="h-4 w-4" />
                      </button>
                      <button 
                        onClick={() => handlePrint(inv.billNo)}
                        className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-md transition-colors focus:outline-none"
                        title="Print Invoice"
                      >
                        <Printer className="h-4 w-4" />
                      </button>
                    </div>
                  </td>
                  
                </tr>
              ))}

              {MOCK_INVOICES.length === 0 && (
                <tr>
                  <td colSpan="6" className="px-5 py-12 text-center text-gray-500">
                    No invoices found in the system.
                  </td>
                </tr>
              )}
            </tbody>
            
          </table>
        </div>
      </div>

    </div>
  );
};

export default Invoices;
